#### **NumPy**
- Numpy stands for *Numerical Python* & is the core library for scientific computing in Python.
- Central object in the NumPy library is the NumPy array which is a multidimensional or n-dimensional array(commonly known as ndarray) object.
- Designed specifically to do mathematical operations, linear algebra & probability calculations.
- Most of the popular libraries such as Pandas, matplotlib & Scikit Learn are built with NumPy as the base.

##### Installing & Importing NumPy

In [1]:
# installing numpy. 
# %pip install numpy

In [2]:
# importing numpy.
import numpy as np

# checking the current version on numpy.
np.__version__

'1.22.0'

##### Creating a NumPy ndarray object

In [3]:
# using a list to create an 1d array : An array that has 0d arrays as its elements.
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# using a tuple to create an 1d array
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# create an 0d array or scalar.
arr = np.array(40)
print(arr)
print(type(arr))

40
<class 'numpy.ndarray'>


In [6]:
# create a 2d array : An array that has 1d arrays as its elements.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [7]:
# create a 3d array: An array that has 2d arrays as its elements.
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(arr)
print(type(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


##### Checking Array Structure

In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])

# checking number of dimensions of an array.
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
# checking total number of elements in an array.
print(a.size)
print(b.size)
print(c.size)
print(d.size)

1
5
6
12


In [10]:
# checking shape of the array. (rows, columns)
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


In [11]:
# checking datatype & size in bytes of each element.
print(a.dtype)
print(a.itemsize)
print(b.dtype)
print(b.itemsize)
print(c.dtype)
print(c.itemsize)
print(d.dtype)
print(d.itemsize)

# we can explicitly mention the data type of elements while creating an array.
arr = np.array([1, 2, 3, 4, 5], dtype = 'S') # string data type.
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4, 5], dtype = 'f') # float data type.
print(arr)
print(arr.dtype)

# we can also convert the datatype of elements present in an array by making a copy of the array using the astype() method.
arr = np.array([1.1, 2.2, 3.3]) # float to integer
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

arr = np.array([1, 0, 1]) # integer to bool.
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

int64
8
int64
8
int64
8
int64
8
[b'1' b'2' b'3' b'4' b'5']
|S1
[1. 2. 3. 4. 5.]
float32
[1 2 3]
int32
[ True False  True]
bool


##### 

##### Array Indexing

In [12]:
# accessing elements of a 1d array : similar to a list or a tuple.
arr = np.array([1, 2, 3, 4, 5])

print(arr[0])
print(arr[2])
print(arr[-1])
print(arr[-2])

1
3
5
4


In [13]:
# accessing elements of a 2d array.
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr)

# getting a specific element. [row index, column index]
print(arr[1, 3])
print(arr[0, 1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9
2


In [14]:
# accessing elements of a 3d array.
arr = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print(arr)

# getting a specific element. [outer row index, inner row index, element index]
print(arr[0, 1, 1])
print(arr[1, 1, 0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
7


##### Array Slicing

In [15]:
# slicing elements of a 1d array : similar to a list or a tuple.
arr = np.array([1, 2, 3, 4, 5])
print(arr)

print(arr[1:4])
print(arr[2:])
print(arr[:3])
print(arr[-4:-2])
print(arr[::2])
print(arr[::-1])

[1 2 3 4 5]
[2 3 4]
[3 4 5]
[1 2 3]
[2 3]
[1 3 5]
[5 4 3 2 1]


In [16]:
# slicing elements of a 2d array.
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr)

# getting a specific row.
print(arr[0, :])

# getting a specific range of elements in a row. 
print(arr[1, 1:4])

# getting a specific column.
print(arr[:, 2])

# getting specific range of elements from columns.
print(arr[:, 1:4])

# getting specific range of elements in a specified sequence from columns.
print(arr[:, ::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
[[ 1  3  5]
 [ 6  8 10]]


In [17]:
# slicing elements of a 3d array.
arr = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print(arr)

# getting all subrows from a specific row.
print(arr[0, :])

# getting elements from a column in all subrows from all rows.
print(arr[:, :, 0])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2]
 [3 4]]
[[1 3]
 [5 7]]


##### Replacing elements of an Array

In [18]:
# 1d array example.
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# replacing a single element
arr[2] = 7
print(arr)

# replacing a range of elements
arr[:3] = [11, 12, 13]
print(arr)
arr[3:] = [14, 15]
print(arr)

[1 2 3 4 5]
[1 2 7 4 5]
[11 12 13  4  5]
[11 12 13 14 15]


In [19]:
# 2d array example.
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr)

# replacing a element in a specified row.
arr[0, 3] = 15
print(arr)

# replacing elements in a specified column.
arr[:, 2] = [20, 25]
print(arr)

# replacing range of elements in a specified row.
arr[1, 1:3] = [35, 40]
print(arr)

# replacing range of elements in a specified column.
arr[:, 1:4] = [[50, 60, 70], [80, 90, 100]]
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3 15  5]
 [ 6  7  8  9 10]]
[[ 1  2 20 15  5]
 [ 6  7 25  9 10]]
[[ 1  2 20 15  5]
 [ 6 35 40  9 10]]
[[  1  50  60  70   5]
 [  6  80  90 100  10]]


In [20]:
# 3d array example.
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(arr)

# replacing a element in a specified inner row.
arr[0, 1, 2] = 15
print(arr)

# # replacing elements in a specified column.
arr[:, :, 2] = [[10, 20], [30, 40]]
print(arr)

# # replacing range of elements in a specified inner row.
arr[0, 1, :2] = [70, 80]
print(arr)

# # replacing range of elements in a specified column.
arr[:, :, :] = [[[15, 20, 25], [25, 30, 35]], [[35, 40, 45], [45, 50, 55]]]
print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5 15]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2 10]
  [ 4  5 20]]

 [[ 7  8 30]
  [10 11 40]]]
[[[ 1  2 10]
  [70 80 20]]

 [[ 7  8 30]
  [10 11 40]]]
[[[15 20 25]
  [25 30 35]]

 [[35 40 45]
  [45 50 55]]]


##### Initializing different kinds of Arrays

In [21]:
# intializing NumPy array with zeroes.
arr = np.zeros((2, 3))
print(arr)

arr = np.zeros((5, 5))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
# intializing NumPy array with all ones.
arr = np.ones((2, 3))
print(arr)

arr = np.ones((3, 2, 2), dtype='i')
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [23]:
# intializing NumPy array having the same number.
arr = np.full((2, 2), 7)
print(arr)

arr = np.full((4, 2, 2), 5)
print(arr)

# using full_like.
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr)
arr_new = np.full_like(arr, 3)
print(arr_new)

[[7 7]
 [7 7]]
[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]

 [[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[3 3 3 3 3]
 [3 3 3 3 3]]


In [24]:
# intializing array within a range.
arr = np.arange(10, 20)
print(arr)

arr = np.arange(10, 100, 10)
print(arr)

# using linspace to generate specified number of random decimal numbers within a specified range.
arr = np.linspace(1, 10, 5)
print(arr)

[10 11 12 13 14 15 16 17 18 19]
[10 20 30 40 50 60 70 80 90]
[ 1.    3.25  5.5   7.75 10.  ]


In [35]:
# intializing an identity matrix.
arr = np.identity(4)
print(arr)

# estimating the cosine value of an array.
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.cos(arr)
print(new_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [26]:
# intializing NumPy arrays with random numbers.

# generates an array containing 10 random integers within the range from 1 to 100.
arr = np.random.randint(1, 100, 10)
print(arr)

arr = np.random.randint(1, 10, size=(3, 3))
print(arr)

# generating an array containing random decimal numbers.
arr = np.random.rand(4, 2)
print(arr)

[28 80 14 78 65  1 79 91 53 70]
[[2 5 1]
 [4 1 7]
 [7 8 3]]
[[0.85965663 0.19120842]
 [0.94322828 0.73825151]
 [0.20822604 0.38155962]
 [0.39801224 0.10169139]]


In [27]:
# intializing an array consisting of repeated elements.
arr = np.array([[7, 8, 9]])
print(arr)
new_arr = np.repeat(arr, 2, axis=0)
print(new_arr)
new_arr = np.repeat(arr, 2, axis=1)
print(new_arr)

# transposing an array.
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr)
arr_trans = arr.transpose()
print(arr_trans)

[[7 8 9]]
[[7 8 9]
 [7 8 9]]
[[7 7 8 8 9 9]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


##### Copying Arrays

In [28]:
arr_org = np.array([1, 2, 3])

# this just copies the reference, so be careful..!!
arr_copy = arr_org

# any changes in the copy will also get reflected in the original.
arr_copy[1] = 5
print(arr_copy)
print(arr_org)

# use copy() method to create an actual copy
arr_org = np.array([1, 2, 3])
arr_copy = arr_org.copy()

# now any changes in the copy will not affect the original
arr_copy[0] = 7
print(arr_copy)
print(arr_org)

[1 5 3]
[1 5 3]
[7 2 3]
[1 2 3]


##### Joining NumPy Arrays

In [73]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# vertical joining using vstack() method.
new_arr = np.vstack((arr1, arr2))
print(new_arr)

# horizontal joining using vstack() method.
new_arr = np.hstack((arr1, arr2))
print(new_arr) 

# columnwise joining using column_stack() method.
new_arr = np.column_stack((arr1, arr2))
print(new_arr)

# joining arrays using concatenation.
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7, 8]])
arr_concat = np.concatenate((arr1, arr2))
print(arr_concat)
arr_concat = np.concatenate((arr1, arr2), axis = 1)
print(arr_concat)

# in case we need add a new column to the concatenated array.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
arr_concat = np.concatenate((arr1, arr2))
print(arr_concat)
arr_new = np.concatenate((arr1, arr2.T), axis = 1)
print(arr_new)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


##### NumPy Array Intersection & Difference

In [30]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

# array intersection.
new_arr = np.intersect1d(arr1, arr2)
print(new_arr)

# array difference.
new_arr = np.setdiff1d(arr1, arr2)
print(new_arr)
new_arr = np.setdiff1d(arr2, arr1)
print(new_arr)

[3 4]
[1 2]
[5 6]


##### Mathematical Operations in NumPy Array 

In [43]:
# addition of arrays : returns the overall sum of the array elements.
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
arr_sum = np.sum([arr1, arr2])
print(arr_sum)

# row-wise sum of the array elements.
arr_rowsum = np.sum([arr1, arr2], axis = 1)
print(arr_rowsum)

# column-wise sum of the array elements.
arr_colsum = np.sum([arr1, arr2], axis = 0)
print(arr_colsum)

# calculating the max, min.
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
arr_max = np.max(arr)
print(arr_max)
arr_max = np.max(arr, axis = 0)
print(arr_max)
arr_max = np.max(arr, axis = 1)
print(arr_max)

arr_min = np.min(arr)
print(arr_min)
arr_min = np.min(arr, axis = 0)
print(arr_min)
arr_min = np.min(arr, axis = 1)
print(arr_min)

28
[10 18]
[ 4  6  8 10]
[[1 2 3 4]
 [5 6 7 8]]
8
[5 6 7 8]
[4 8]
1
[1 2 3 4]
[1 5]


In [34]:
# addition of an array with a scalar value.
arr = np.array([10, 15, 20, 25])
arr = arr + 10
print(arr)

# multiplication of an array with a scalar value.
arr = np.array([10, 15, 20, 25])
arr = arr * 10
print(arr)

# subtraction of an array with a scalar value.
arr = np.array([10, 15, 20, 25])
arr = arr - 5
print(arr)

# division of an array with a scalar value.
arr = np.array([10, 15, 20, 25])
arr = arr / 5
print(arr)

# exponentation of an array with a scalar value.
arr = np.array([10, 15, 20, 25])
arr = arr ** 2
print(arr)

[20 25 30 35]
[100 150 200 250]
[ 5 10 15 20]
[2. 3. 4. 5.]
[100 225 400 625]


In [33]:
arr = np.array([10, 15, 20, 25, 50])

# finding the mean of the elements in an array.
print(np.mean(arr))

# finding the median of the elements in an array.
print(np.median(arr))

# finding the standard deviation of the elements in an array.
print(np.std(arr))

24.0
20.0
13.92838827718412


In [50]:
# matrix multiplication.
arr1 = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
print(arr1)
arr2 = np.array([[10, 11, 12], [13, 14, 15],[16, 17, 18]])
print(arr2)

arr_multi = arr1.dot(arr2)
print(arr_multi)

arr_multi = arr2.dot(arr1)
print(arr_multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[[138 171 204]
 [174 216 258]
 [210 261 312]]


##### Reshaping Arrays.

In [56]:
arr = np.arange(1, 9)
print(arr)
print(arr.shape)

arr_reshaped = arr.reshape((2, 4))
print(arr_reshaped)
print(arr_reshaped.shape)

arr_reshaped = arr.reshape((4, 2))
print(arr_reshaped)
print(arr_reshaped.shape)

arr_reshaped = arr.reshape((8, 1))
print(arr_reshaped)
print(arr_reshaped.shape)

[1 2 3 4 5 6 7 8]
(8,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)


##### Broadcasting

In [76]:
# enables the user to perform aritmetic operations with arrays of different shapes.
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr2 = np.array([1, 2, 3])
arr_new = arr1 + arr2 # here we added elements of arr2 to each row of arr1.
print(arr_new)

# similarly we can do other aritmetic operations as well.
arr_new = arr1 * arr2
print(arr_new)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]
 [10 22 36]]


##### Saving & Loading data to / from files with NumPy 

In [77]:
# saving data to a file.
arr = np.array([10, 15, 20, 25, 30])
np.save('arr_new', arr)

In [78]:
# loading data from a file
arr_org = np.load('arr_new.npy')
print(arr_org)

[10 15 20 25 30]


##### Boolean Masking & Advanced Indexing

In [96]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr)

# boolean masking.
print(arr > 5)

# filtering data basis the boolean condition.
arr_filtered = arr[arr > 5]
print(arr_filtered)

# filtering basis multiple boolean conditions.
arr_filtered = arr[(arr > 5) & (arr < 10)]
print(arr_filtered)

arr_filtered = arr[(arr > 8) | (arr > 10)]
print(arr_filtered)

# we can use the tilde(~) to return result not matching with the specified boolean condition.
arr_filtered = arr[~(arr >= 10)]
print(arr_filtered)

arr_filtered = arr[~((arr > 8) | (arr > 10))]
print(arr_filtered)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]
[ 6  7  8  9 10 11 12]
[6 7 8 9]
[ 9 10 11 12]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8]
